# Generated by Django 3.2.20 on 2023-12-21 20:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("can_be_closed", models.BooleanField()),
                ("text", models.TextField()),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (1, "very_high"),
                            (2, "high"),
                            (3, "medium"),
                            (4, "low"),
                            (5, "very_low"),
                        ]
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
