# Generated by Django 3.2.18 on 2023-03-23 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TemplateType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "level",
                    models.CharField(
                        choices=[("low", 1), ("medium", 2), ("high", 3)], max_length=255
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TemplateFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Flows", "Flows"),
                            ("Integrations", "Integrations"),
                            ("Intelligences", "Intelligences"),
                        ],
                        max_length=255,
                    ),
                ),
                ("feature_identifier", models.CharField(max_length=255)),
                (
                    "template_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_features",
                        to="template_projects.templatetype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TemplateAI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "template_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_ais",
                        to="template_projects.templatetype",
                    ),
                ),
            ],
        ),
    ]
