# Generated by Django 3.2.18 on 2023-03-30 20:10

import connect.template_projects.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_projects', '0002_templatetype_setup'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatetype',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=connect.template_projects.storage.TemplateTypeImageStorage(), upload_to=''),
        ),
    ]
