# Generated by Django 3.2.18 on 2023-06-05 19:45

import connect.template_projects.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('template_projects', '0003_templatetype_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatefeature',
            name='template_type',
        ),
        migrations.AddField(
            model_name='templatefeature',
            name='template_type',
            field=models.ManyToManyField(related_name='template_features', to='template_projects.TemplateType'),
        ),
        migrations.CreateModel(
            name='TemplateFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('flow_url', models.FileField(storage=connect.template_projects.storage.TemplateFlowFileStorage(), upload_to='')),
                ('template_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_flows', to='template_projects.templatetype')),
            ],
        ),
    ]
