# Generated by Django 3.2.20 on 2023-08-21 18:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('template_projects', '0003_templatetype_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatetype',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='UUID'),
        ),
    ]
