# Generated by Django 3.2.20 on 2023-08-22 12:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("template_projects", "0003_templatetype_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="templatetype",
            name="photo_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="templatetype",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, verbose_name="UUID"),
        ),
    ]
