# Generated by Django 3.2.20 on 2023-07-26 18:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('template_projects', '0003_templatetype_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatetype',
            name='id',
        ),
        migrations.AddField(
            model_name='templatetype',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
    ]
