# Generated by Django 3.2.18 on 2023-06-06 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('template_projects', '0004_auto_20230605_1945'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemplateAI',
        ),
    ]
