# Generated by Django 3.2.20 on 2023-08-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("template_projects", "0004_auto_20230822_1258"),
    ]

    operations = [
        migrations.AddField(
            model_name="templatetype",
            name="base_project_uuid",
            field=models.UUIDField(blank=True, null=True, verbose_name="base project"),
        ),
    ]
