# Generated by Django 3.2.20 on 2023-09-05 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("template_projects", "0005_templatetype_base_project_uuid"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TemplateAI",
        ),
    ]
