# Generated by Django 3.2.20 on 2023-09-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_projects', '0005_templatetype_base_project_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatetype',
            name='extra_fields',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
