# Generated by Django 3.2.20 on 2023-09-08 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('template_projects', '0006_templatetype_extra_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatetype',
            name='extra_fields',
        ),
    ]
