# Generated by Django 3.2.23 on 2024-09-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_projects', '0007_auto_20230926_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatetype',
            name='language',
            field=models.CharField(choices=[('en-us', 'English'), ('pt-br', 'Portuguese'), ('es', 'Spanish')], default='pt-br', max_length=10, verbose_name='language'),
        ),
    ]
