# Generated by Django 3.2.23 on 2024-09-13 19:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "template_projects",
            "0008_templatefeaturetranslation_templatetypetranslation",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="templatetypetranslation",
            name="category",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255), default=list, size=None
            ),
        ),
        migrations.AlterUniqueTogether(
            name="templatefeaturetranslation",
            unique_together={("language", "template_feature")},
        ),
        migrations.AlterUniqueTogether(
            name="templatetypetranslation",
            unique_together={("language", "template_type")},
        ),
    ]
