# Generated by Django 3.2.23 on 2026-05-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_projects', '0009_auto_20240913_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatefeaturetranslation',
            name='language',
            field=models.CharField(choices=[('en-us', 'English'), ('pt-br', 'Portuguese'), ('es', 'Spanish'), ('ro', 'Romanian')], default='en-us', max_length=10, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='templatetypetranslation',
            name='language',
            field=models.CharField(choices=[('en-us', 'English'), ('pt-br', 'Portuguese'), ('es', 'Spanish'), ('ro', 'Romanian')], default='en-us', max_length=10, verbose_name='language'),
        ),
    ]
