fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-ast
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: no-commit-to-branch
        args: [--branch=main]

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8

  - repo: https://github.com/IamTheFij/docker-pre-commit
    rev: v3.0.1
    hooks:
      - id: docker-compose-check

  - repo: https://gitlab.com/smop/pre-commit-hooks
    rev: v1.0.0
    hooks:
      - id: check-poetry

  - repo: local
    hooks:
      - id: tests
        name: "Running unit tests"
        entry: poetry run python manage.py test -v2 --noinput
        verbose: true
        pass_filenames: false
        language: system
