# Generated by Django 2.2.17 on 2020-12-29 15:08

from django.db import migrations, models
import weni.storages


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_user_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="photo",
            field=models.FileField(
                null=True,
                storage=weni.storages.AvatarUserMediaStorage(),
                upload_to="",
                verbose_name="photo user",
            ),
        ),
    ]
