# Generated by Django 2.2.19 on 2021-07-16 13:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_user_last_update_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="utm",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=dict, verbose_name="UTM Marketing"
            ),
        ),
    ]
