# Generated by Django 2.2.19 on 2021-07-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_user_utm"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_marketing",
            field=models.BooleanField(
                default=True, verbose_name="Allows receiving marketing emails"
            ),
        ),
    ]
