# Generated by Django 3.2.6 on 2021-08-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_user_email_marketing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="utm",
            field=models.JSONField(default=dict, verbose_name="UTM Marketing"),
        ),
    ]
