# Generated by Django 2.2.17 on 2021-02-26 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import timezone_field.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=36, verbose_name="title")),
                ("description", models.TextField(verbose_name="description")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
            ],
            options={
                "verbose_name": "dashboard newsletter",
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="organization name"),
                ),
                (
                    "description",
                    models.TextField(verbose_name="organization description"),
                ),
                (
                    "inteligence_organization",
                    models.IntegerField(verbose_name="inteligence organization id"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "organization",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="project name")),
                (
                    "timezone",
                    timezone_field.fields.TimeZoneField(verbose_name="Timezone"),
                ),
                (
                    "date_format",
                    models.CharField(
                        choices=[("D", "DD-MM-YYYY"), ("M", "MM-DD-YYYY")],
                        default="D",
                        help_text="Whether day comes first or month comes first in dates",
                        max_length=1,
                        verbose_name="Date Format",
                    ),
                ),
                (
                    "flow_organization",
                    models.UUIDField(
                        unique=True, verbose_name="flow identification UUID"
                    ),
                ),
                (
                    "flow_organization_id",
                    models.IntegerField(
                        null=True, verbose_name="flow identification UUID"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project",
                        to="common.Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "project",
                "unique_together": {("flow_organization", "flow_organization_id")},
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(unique=True, verbose_name="service url")),
                (
                    "status",
                    models.BooleanField(default=False, verbose_name="status service"),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("type_service_flows", "Flows service"),
                            ("type_service_inteligence", "Inteligence Service"),
                            ("type_service_chat", "Chat Service"),
                        ],
                        default="type_service_chat",
                        max_length=50,
                        verbose_name="service type",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="last updated"
                    ),
                ),
                (
                    "default",
                    models.BooleanField(
                        default=False, verbose_name="standard service for all projects"
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("region_ireland", "Region Ireland"),
                            ("region_virginia", "Region Virginia"),
                            ("region_sao_paulo", "Region São Paulo"),
                        ],
                        default="region_sao_paulo",
                        max_length=50,
                        verbose_name="service region",
                    ),
                ),
            ],
            options={
                "verbose_name": "service",
            },
        ),
        migrations.CreateModel(
            name="ServiceStatus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_status",
                        to="common.Project",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="common.Service"
                    ),
                ),
            ],
            options={
                "verbose_name": "service status",
                "ordering": ["created_at"],
                "unique_together": {("service", "project")},
            },
        ),
        migrations.CreateModel(
            name="OrganizationAuthorization",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "role",
                    models.PositiveIntegerField(
                        choices=[
                            (0, "not set"),
                            (1, "viewer"),
                            (2, "contributor"),
                            (3, "admin"),
                        ],
                        default=0,
                        verbose_name="role",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authorizations",
                        to="common.Organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "organization authorization",
                "verbose_name_plural": "organization authorizations",
                "unique_together": {("user", "organization")},
            },
        ),
    ]
