# Generated by Django 2.2.17 on 2020-12-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="rocket_chat",
            field=models.BooleanField(default=False, verbose_name="rocket chat"),
        ),
    ]
