# Generated by Django 2.2.17 on 2021-01-06 18:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_service_rocket_chat"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="last_updated",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="last updated",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="service",
            name="rocket_chat",
            field=models.BooleanField(
                default=False, verbose_name="is it a rocketchat server?"
            ),
        ),
    ]
