# Generated by Django 2.2.19 on 2021-03-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_organization_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationauthorization',
            name='role',
            field=models.PositiveIntegerField(choices=[(1, 'viewer'), (2, 'contributor'), (3, 'admin')], default=1, verbose_name='role'),
        ),
    ]
