# Generated by Django 2.2.17 on 2021-01-14 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("common", "0003_auto_20210106_1826"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicestatus",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="common.Service"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="servicestatus",
            unique_together={("service", "user")},
        ),
    ]
