# Generated by Django 2.2.19 on 2021-03-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0007_auto_20210325_1410"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="maintenance",
            field=models.BooleanField(
                default=False, verbose_name="Define if the service is under maintenance"
            ),
        ),
    ]
