# Generated by Django 2.2.19 on 2021-04-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0011_auto_20210416_1525"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="contact_count",
            field=models.IntegerField(default=0, verbose_name="Contacts count"),
        ),
        migrations.AddField(
            model_name="project",
            name="flow_count",
            field=models.IntegerField(default=0, verbose_name="Flows count"),
        ),
        migrations.AddField(
            model_name="project",
            name="inteligence_count",
            field=models.IntegerField(default=0, verbose_name="Intelligence count"),
        ),
    ]
