# Generated by Django 2.2.19 on 2021-04-26 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0014_auto_20210426_1358"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="newsletterlanguage",
            unique_together={("language", "newsletter")},
        ),
    ]
