# Generated by Django 2.2.19 on 2021-05-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0020_auto_20210513_1829"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestpermissionorganization",
            name="role",
            field=models.PositiveIntegerField(
                choices=[
                    (0, "not set"),
                    (1, "viewer"),
                    (2, "contributor"),
                    (3, "admin"),
                ],
                default=0,
                verbose_name="role",
            ),
        ),
    ]
