# Generated by Django 2.2.19 on 2021-05-24 18:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0021_requestpermissionorganization_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="start_maintenance",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="date start maintenance",
            ),
            preserve_default=False,
        ),
    ]
