# Generated by Django 2.2.19 on 2021-07-20 18:28
from datetime import timedelta

from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


def noop(apps, schema_editor):  # pragma: no cover
    pass


def migrate(apps, schema_editor):  # pragma: no cover
    Organization = apps.get_model("common", "Organization")

    for org in Organization.objects.all():
        org.organization_billing.create(next_due_date=timezone.now().date())


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0022_service_start_maintenance"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("due_date", models.DateField(null=True, verbose_name="due date")),
                ("paid_date", models.DateField(null=True, verbose_name="paid date")),
                (
                    "credit",
                    models.DecimalField(
                        decimal_places=2, max_digits=2, null=True, verbose_name="credit"
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("paid", "paid"),
                            ("canceled", "canceled"),
                            ("fraud", "fraud"),
                        ],
                        default="pending",
                        max_length=8,
                        verbose_name="payment status",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("credit_card", "credit card"),
                            ("payment_slip", "payment slip"),
                        ],
                        default="credit_card",
                        max_length=12,
                        verbose_name="payment method",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="notes"),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=2,
                        verbose_name="tax rate",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_billing_invoice",
                        to="common.Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "organization billing invoice",
            },
        ),
        migrations.CreateModel(
            name="InvoiceProject",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_random_id",
                    models.IntegerField(
                        default=1, verbose_name="incremental invoice amount"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=2, verbose_name="amount"
                    ),
                ),
                (
                    "contact_count",
                    models.IntegerField(default=0, verbose_name="active contact count"),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_billing_invoice_project",
                        to="common.Invoice",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="common.Project"
                    ),
                ),
            ],
            options={
                "verbose_name": "organization billing invoice project",
            },
        ),
        migrations.CreateModel(
            name="BillingPlan",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cycle",
                    models.CharField(
                        choices=[
                            ("billing_free", "free"),
                            ("billing_single", "single"),
                            ("billing_monthly", "monthly"),
                            ("billing_quarterly", "quarterly"),
                            ("billing_semester", "semester"),
                            ("billing_annual", "annual"),
                            ("billing_bienal", "bienal"),
                            ("billing_trienal", "trienal"),
                        ],
                        default="billing_monthly",
                        max_length=20,
                        verbose_name="billing cycle",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("credit_card", "credit card"),
                            ("payment_slip", "payment slip"),
                        ],
                        default="credit_card",
                        max_length=12,
                        verbose_name="payment method",
                    ),
                ),
                (
                    "next_due_date",
                    models.DateField(null=True, verbose_name="next due date"),
                ),
                (
                    "termination_date",
                    models.DateField(null=True, verbose_name="termination date"),
                ),
                (
                    "credit",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=2, verbose_name="credit"
                    ),
                ),
                (
                    "notes_administration",
                    models.TextField(
                        blank=True, null=True, verbose_name="notes administration"
                    ),
                ),
                (
                    "fixed_discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=2,
                        verbose_name="fixed discount",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_billing",
                        to="common.Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "organization billing plan",
            },
        ),
        migrations.AlterUniqueTogether(
            name="billingplan",
            unique_together={("organization",)},
        ),
        migrations.RunPython(migrate, noop),
    ]
