# Generated by Django 3.2.6 on 2021-08-10 14:42

from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


def noop(apps, schema_editor):  # pragma: no cover
    pass


def migrate(apps, schema_editor):  # pragma: no cover
    Organization = apps.get_model("common", "Organization")

    for org in Organization.objects.all():
        org.organization_billing.create(next_due_date=timezone.now().date())


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0022_service_start_maintenance"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_random_id",
                    models.IntegerField(
                        default=1, verbose_name="incremental invoice amount"
                    ),
                ),
                ("due_date", models.DateField(null=True, verbose_name="due date")),
                ("paid_date", models.DateField(null=True, verbose_name="paid date")),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("paid", "paid"),
                            ("canceled", "canceled"),
                            ("fraud", "fraud"),
                        ],
                        default="pending",
                        max_length=8,
                        verbose_name="payment status",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("credit_card", "credit card"),
                            ("payment_slip", "payment slip"),
                        ],
                        max_length=12,
                        null=True,
                        verbose_name="payment method",
                    ),
                ),
                ("discount", models.FloatField(default=0, verbose_name="discount")),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="notes"),
                ),
                (
                    "stripe_charge",
                    models.CharField(
                        blank=True,
                        help_text="The Stripe charge id for this charge",
                        max_length=32,
                        null=True,
                        verbose_name="Stripe Charge Id",
                    ),
                ),
            ],
            options={
                "verbose_name": "organization billing invoice",
            },
        ),
        migrations.AddField(
            model_name="organization",
            name="is_suspended",
            field=models.BooleanField(
                default=False,
                help_text="Whether this organization is currently suspended.",
            ),
        ),
        migrations.CreateModel(
            name="InvoiceProject",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=11,
                        verbose_name="amount",
                    ),
                ),
                (
                    "contact_count",
                    models.IntegerField(default=0, verbose_name="active contact count"),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_billing_invoice_project",
                        to="common.invoice",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="common.project"
                    ),
                ),
            ],
            options={
                "verbose_name": "organization billing invoice project",
            },
        ),
        migrations.AddField(
            model_name="invoice",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organization_billing_invoice",
                to="common.organization",
            ),
        ),
        migrations.CreateModel(
            name="BillingPlan",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cycle",
                    models.CharField(
                        choices=[
                            ("billing_free", "free"),
                            ("billing_single", "single"),
                            ("billing_monthly", "monthly"),
                            ("billing_quarterly", "quarterly"),
                            ("billing_semester", "semester"),
                            ("billing_annual", "annual"),
                            ("billing_bienal", "bienal"),
                            ("billing_trienal", "trienal"),
                        ],
                        default="billing_monthly",
                        max_length=20,
                        verbose_name="billing cycle",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("credit_card", "credit card"),
                            ("payment_slip", "payment slip"),
                        ],
                        max_length=12,
                        null=True,
                        verbose_name="payment method",
                    ),
                ),
                (
                    "next_due_date",
                    models.DateField(null=True, verbose_name="next due date"),
                ),
                (
                    "termination_date",
                    models.DateField(null=True, verbose_name="termination date"),
                ),
                (
                    "notes_administration",
                    models.TextField(
                        blank=True, null=True, verbose_name="notes administration"
                    ),
                ),
                (
                    "fixed_discount",
                    models.FloatField(default=0, verbose_name="fixed discount"),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[("free", "free"), ("enterprise", "enterprise")],
                        max_length=10,
                        verbose_name="plan",
                    ),
                ),
                (
                    "stripe_customer",
                    models.CharField(
                        blank=True,
                        help_text="Our Stripe customer id for your organization",
                        max_length=32,
                        null=True,
                        verbose_name="Stripe Customer",
                    ),
                ),
                (
                    "stripe_configured_card",
                    models.BooleanField(
                        default=False, verbose_name="Stripe Customer Configured Card"
                    ),
                ),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_billing",
                        to="common.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "organization billing plan",
                "unique_together": {("organization",)},
            },
        ),
        migrations.RunPython(migrate, noop),
    ]
