# Generated by Django 3.2.6 on 2021-08-26 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0023_auto_20210824_1503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logservice',
            options={'verbose_name': 'log service', 'verbose_name_plural': 'log services'},
        ),
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name': 'newsletter', 'verbose_name_plural': 'newsletters'},
        ),
        migrations.AlterModelOptions(
            name='newsletterlanguage',
            options={'verbose_name': 'dashboard newsletter language', 'verbose_name_plural': 'newsletter languages'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'organization', 'verbose_name_plural': 'organizations'},
        ),
    ]
