# Generated by Django 2.2.19 on 2021-07-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0023_billingplan_invoice_invoiceproject"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoiceproject",
            name="invoice_random_id",
        ),
        migrations.AddField(
            model_name="invoice",
            name="invoice_random_id",
            field=models.IntegerField(
                default=1, verbose_name="incremental invoice amount"
            ),
        ),
        migrations.AlterField(
            model_name="billingplan",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("credit_card", "credit card"),
                    ("payment_slip", "payment slip"),
                ],
                max_length=12,
                null=True,
                verbose_name="payment method",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("credit_card", "credit card"),
                    ("payment_slip", "payment slip"),
                ],
                max_length=12,
                null=True,
                verbose_name="payment method",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceproject",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=11, verbose_name="amount"
            ),
        ),
    ]
