# Generated by Django 3.2.6 on 2021-08-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0023_auto_20210810_1442"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingplan",
            name="card_brand",
            field=models.CharField(
                blank=True, max_length=24, null=True, verbose_name="Card Brand"
            ),
        ),
        migrations.AddField(
            model_name="billingplan",
            name="card_expiration_date",
            field=models.CharField(
                blank=True, max_length=6, null=True, verbose_name="Card Expiration Date"
            ),
        ),
        migrations.AddField(
            model_name="billingplan",
            name="cardholder_name",
            field=models.TextField(
                blank=True, null=True, verbose_name="Cardholder Name"
            ),
        ),
        migrations.AddField(
            model_name="billingplan",
            name="final_card_number",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Final Card Number"
            ),
        ),
    ]
