# Generated by Django 3.2.6 on 2021-08-12 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0024_auto_20210812_1244"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentLogs",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                ("status", models.BooleanField(verbose_name="status")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_paymentlogs",
                        to="common.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "payment log",
            },
        ),
    ]
