# Generated by Django 2.2.19 on 2021-07-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0024_auto_20210721_1930"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingplan",
            name="fixed_discount",
            field=models.FloatField(default=0, verbose_name="fixed discount"),
        ),
    ]
