# Generated by Django 3.2.6 on 2021-08-12 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0025_paymentlogs"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PaymentLogs",
        ),
    ]
