# Generated by Django 2.2.19 on 2021-07-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0025_auto_20210722_1743"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="credit",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="tax_rate",
        ),
        migrations.AddField(
            model_name="invoice",
            name="discount",
            field=models.FloatField(default=0, verbose_name="discount"),
        ),
    ]
