# Generated by Django 3.2.6 on 2021-08-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0026_delete_paymentlogs"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="capture_payment",
            field=models.BooleanField(
                default=True,
                help_text="Controls whether the system will capture the payment, if not successful, the user will receive an alert to adjust the payment data",
            ),
        ),
    ]
