# Generated by Django 2.2.19 on 2021-07-22 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0026_auto_20210722_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingplan',
            name='credit',
        ),
    ]
