# Generated by Django 2.2.19 on 2021-07-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0027_remove_billingplan_credit"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingplan",
            name="plan",
            field=models.CharField(
                choices=[("free", "free"), ("enterprise", "enterprise")],
                default="free",
                max_length=10,
                verbose_name="plan",
            ),
            preserve_default=False,
        ),
    ]
