# Generated by Django 2.2.24 on 2021-07-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0029_billingplan_stripe_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="stripe_charge",
            field=models.CharField(
                blank=True,
                help_text="The Stripe charge id for this charge",
                max_length=32,
                null=True,
                verbose_name="Stripe Charge Id",
            ),
        ),
    ]
