# Generated by Django 3.2.6 on 2021-08-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0029_invoice_cost_per_whatsapp"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingplan",
            name="last_invoice",
            field=models.DateField(null=True, verbose_name="last invoice"),
        ),
    ]
