# Generated by Django 2.2.24 on 2021-07-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0030_invoice_stripe_charge"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="is_suspended",
            field=models.BooleanField(
                default=False,
                help_text="Whether this organization is currently suspended.",
            ),
        ),
    ]
