# Generated by Django 2.2.24 on 2021-07-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0030_invoice_stripe_charge"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingplan",
            name="stripe_configured_card",
            field=models.BooleanField(
                default=False, verbose_name="Stripe Customer Configured Card"
            ),
        ),
    ]
