# Generated by Django 3.2.6 on 2021-08-20 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0030_billingplan_last_invoice"),
    ]

    operations = [
        migrations.RenameField(
            model_name="billingplan",
            old_name="last_invoice",
            new_name="last_invoice_date",
        ),
    ]
