# Generated by Django 2.2.24 on 2021-08-03 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0031_billingplan_stripe_configured_card"),
        ("common", "0031_organization_is_suspended"),
    ]

    operations = []
