# Generated by Django 3.2.25 on 2026-07-29 18:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeEvent',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_uuid', models.UUIDField()),
                ('user_email', models.EmailField(max_length=254)),
                ('occurred_at', models.DateTimeField()),
                ('action', models.CharField(choices=[('ADD', 'ADD'), ('CREATE', 'CREATE'), ('UPDATE', 'UPDATE'), ('DELETE', 'DELETE')], max_length=32)),
                ('entity', models.CharField(choices=[('USER', 'USER'), ('FLOW', 'FLOW'), ('CHANNEL', 'CHANNEL'), ('TRIGGER', 'TRIGGER'), ('CAMPAIGN', 'CAMPAIGN')], max_length=32)),
                ('module', models.CharField(choices=[('NEXUS', 'NEXUS'), ('LIVE_DESK', 'LIVE_DESK')], max_length=32)),
                ('object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('object_name', models.CharField(blank=True, max_length=255, null=True)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
        ),
    ]
