# Generated by Django 2.2.17 on 2020-12-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardNewsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=36, verbose_name='name')),
                ('description', models.TextField(default='botinho', verbose_name='icon')),
            ],
            options={
                'verbose_name': 'dashboard newsletter',
            },
        ),
    ]
