# Generated by Django 2.2.19 on 2021-04-26 13:57

from django.db import migrations, models
import django.db.models.deletion


def noop(apps, schema_editor):  # pragma: no cover
    pass


def delete_newsletter(apps, schema_editor):  # pragma: no cover
    Newsletter = apps.get_model("common", "Newsletter")
    Newsletter.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0012_auto_20210423_1242"),
    ]

    operations = [
        migrations.RunPython(delete_newsletter, noop),
        migrations.AlterModelOptions(
            name="newsletterlanguage",
            options={"verbose_name": "dashboard newsletter language"},
        ),
        migrations.RemoveField(
            model_name="newsletter",
            name="newsletter_language",
        ),
        migrations.AddField(
            model_name="newsletterlanguage",
            name="newsletter",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.Newsletter",
            ),
            preserve_default=False,
        ),
    ]
