# Generated by Django 2.2.19 on 2021-04-26 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0013_auto_20210426_1357"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletterlanguage",
            name="newsletter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="newsletter",
                to="common.Newsletter",
            ),
        ),
    ]
