# Generated by Django 2.2.19 on 2021-05-04 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0015_auto_20210426_1406"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationauthorization",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="authorizations_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
