# Generated by Django 2.2.19 on 2021-05-13 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0019_auto_20210512_2021"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="requestpermissionorganization",
            unique_together={("email", "organization")},
        ),
        migrations.RemoveField(
            model_name="requestpermissionorganization",
            name="token",
        ),
    ]
