# Generated by Django 3.2.12 on 2022-03-09 19:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    replaces = [('common', '0024_auto_20210826_1928'), ('common', '0025_billingplan_is_active'), ('common', '0026_genericbillingdata'), ('common', '0026_auto_20211126_1957'), ('common', '0027_merge_0026_auto_20211126_1957_0026_genericbillingdata'), ('common', '0028_auto_20211202_1648'), ('common', '0029_auto_20211202_1729'), ('common', '0030_project_extra_active_integration'), ('common', '0031_billingplan_contract_on'), ('common', '0032_alter_billingplan_plan'), ('common', '0033_auto_20211222_1819'), ('common', '0034_alter_billingplan_plan'), ('common', '0035_alter_newsletterlanguage_language'), ('common', '0036_project_total_contact_count')]

    dependencies = [
        ('common', '0023_auto_20210824_1503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logservice',
            options={'verbose_name': 'log service', 'verbose_name_plural': 'log services'},
        ),
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name': 'newsletter', 'verbose_name_plural': 'newsletters'},
        ),
        migrations.AlterModelOptions(
            name='newsletterlanguage',
            options={'verbose_name': 'dashboard newsletter language', 'verbose_name_plural': 'newsletter languages'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'organization', 'verbose_name_plural': 'organizations'},
        ),
        migrations.AddField(
            model_name='billingplan',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active plan'),
        ),
        migrations.AddField(
            model_name='billingplan',
            name='additional_billing_information',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Additional billing information'),
        ),
        migrations.CreateModel(
            name='GenericBillingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_free_active_contacts_limit', models.PositiveIntegerField(default=200, verbose_name='Free active contacts limit')),
                ('_from_100001_to_250000', models.DecimalField(decimal_places=3, default=0.133, max_digits=11, verbose_name='From 100001 to 250000 active contacts')),
                ('_from_10001_to_30000', models.DecimalField(decimal_places=3, default=0.156, max_digits=11, verbose_name='From 10001 to 30000 active contacts')),
                ('_from_1001_to_5000', models.DecimalField(decimal_places=3, default=0.178, max_digits=11, verbose_name='From 1001 to 5000 active contacts')),
                ('_from_1_to_1000', models.DecimalField(decimal_places=3, default=0.267, max_digits=11, verbose_name='From 1 to 1000 active contacts')),
                ('_from_2500001', models.DecimalField(decimal_places=3, default=0.133, max_digits=11, verbose_name='From 100001 to 250000 active contacts')),
                ('_from_30001_to_50000', models.DecimalField(decimal_places=3, default=0.144, max_digits=11, verbose_name='From 30001 to 50000 active contacts')),
                ('_from_50001_to_100000', models.DecimalField(decimal_places=3, default=0.14, max_digits=11, verbose_name='From 50001 to 100000 active contacts')),
                ('_from_5001_to_10000', models.DecimalField(decimal_places=3, default=0.167, max_digits=11, verbose_name='From 5001 to 10000 active contacts')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='extra_active_integration',
            field=models.IntegerField(default=0, verbose_name='Whatsapp Integrations'),
        ),
        migrations.AddField(
            model_name='billingplan',
            name='contract_on',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2021, 12, 9, 12, 42, 40, 540676, tzinfo=utc), verbose_name='date of contract plan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billingplan',
            name='plan',
            field=models.CharField(choices=[('free', 'free'), ('enterprise', 'enterprise'), ('custom', 'custom')], max_length=10, verbose_name='plan'),
        ),
        migrations.AddField(
            model_name='billingplan',
            name='personal_identification_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Personal Identification Number'),
        ),
        migrations.AlterField(
            model_name='billingplan',
            name='plan',
            field=models.CharField(choices=[('free', 'free'), ('enterprise', 'enterprise'), ('custom', 'custom')], default='custom', max_length=10, verbose_name='plan'),
        ),
        migrations.AlterField(
            model_name='newsletterlanguage',
            name='language',
            field=models.CharField(choices=[('es', 'Spanish'), ('en-us', 'English'), ('pt-br', 'Portuguese')], default='en-us', max_length=10, verbose_name='language'),
        ),
        migrations.AddField(
            model_name='project',
            name='total_contact_count',
            field=models.IntegerField(default=0, verbose_name='Contacts count of all time'),
        ),
    ]
