# Generated by Django 3.2.9 on 2021-11-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0025_billingplan_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingplan',
            name='additional_billing_information',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Additional billing information'),
        ),
        migrations.AddField(
            model_name='billingplan',
            name='cnpj',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='billingplan',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
    ]
