# Generated by Django 3.2.9 on 2021-12-01 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0026_auto_20211126_1957"),
        ("common", "0026_genericbillingdata"),
    ]

    operations = []
