# Generated by Django 3.2.9 on 2021-12-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0027_merge_0026_auto_20211126_1957_0026_genericbillingdata"),
    ]

    operations = [
        migrations.AddField(
            model_name="genericbillingdata",
            name="_from_100001_to_250000",
            field=models.DecimalField(
                decimal_places=2,
                default=0.133,
                max_digits=11,
                verbose_name="From 100001 to 250000 active contacts",
            ),
        ),
        migrations.AddField(
            model_name="genericbillingdata",
            name="_from_10001_to_30000",
            field=models.DecimalField(
                decimal_places=2,
                default=0.156,
                max_digits=11,
                verbose_name="From 10001 to 30000 active contacts",
            ),
        ),
        migrations.AddField(
            model_name="genericbillingdata",
            name="_from_1001_to_5000",
            field=models.DecimalField(
                decimal_places=2,
                default=0.178,
                max_digits=11,
                verbose_name="From 1001 to 5000 active contacts",
            ),
        ),
        migrations.AddField(
            model_name="genericbillingdata",
            name="_from_1_to_1000",
            field=models.DecimalField(
                decimal_places=2,
                default=0.267,
                max_digits=11,
                verbose_name="From 1 to 1000 active contacts",
            ),
        ),
        migrations.AddField(
            model_name="genericbillingdata",
            name="_from_2500001",
            field=models.DecimalField(
                decimal_places=2,
                default=0.133,
                max_digits=11,
                verbose_name="From 100001 to 250000 active contacts",
            ),
        ),
        migrations.AddField(
            model_name="genericbillingdata",
            name="_from_30001_to_50000",
            field=models.DecimalField(
                decimal_places=2,
                default=0.144,
                max_digits=11,
                verbose_name="From 30001 to 50000 active contacts",
            ),
        ),
        migrations.AddField(
            model_name="genericbillingdata",
            name="_from_50001_to_100000",
            field=models.DecimalField(
                decimal_places=2,
                default=0.14,
                max_digits=11,
                verbose_name="From 50001 to 100000 active contacts",
            ),
        ),
        migrations.AddField(
            model_name="genericbillingdata",
            name="_from_5001_to_10000",
            field=models.DecimalField(
                decimal_places=2,
                default=0.167,
                max_digits=11,
                verbose_name="From 5001 to 10000 active contacts",
            ),
        ),
    ]
