# Generated by Django 3.2.9 on 2021-12-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0032_alter_billingplan_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingplan',
            name='cnpj',
        ),
        migrations.RemoveField(
            model_name='billingplan',
            name='cpf',
        ),
        migrations.AddField(
            model_name='billingplan',
            name='personal_identification_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Personal Identification Number'),
        ),
    ]
