# Generated by Django 3.2.11 on 2022-04-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0036_project_total_contact_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletterlanguage",
            name="language",
            field=models.CharField(
                choices=[
                    ("en-us", "English"),
                    ("pt-br", "Portuguese"),
                    ("es", "Spanish"),
                ],
                default="en-us",
                max_length=10,
                verbose_name="language",
            ),
        ),
    ]
