# Generated by Django 3.2.11 on 2022-02-04 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0035_auto_20220202_1214'),
        ('common', '0036_alter_projectauthorization_organization_authorization'),
    ]

    operations = [
    ]
