# Generated by Django 3.2.12 on 2022-04-20 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0037_auto_20220324_1811'),
        ('common', '0037_auto_20220418_2220'),
    ]

    operations = [
    ]
