# Generated by Django 3.2.11 on 2022-02-07 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0037_merge_20220204_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationauthorization',
            name='role',
            field=models.PositiveIntegerField(choices=[(0, 'not set'), (1, 'contributor'), (2, 'admin'), (3, 'financial')], default=0, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='requestpermissionorganization',
            name='role',
            field=models.PositiveIntegerField(choices=[(0, 'not set'), (1, 'contributor'), (2, 'admin'), (3, 'financial')], default=0, verbose_name='role'),
        ),
        migrations.CreateModel(
            name='RequestPermissionProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('role', models.PositiveIntegerField(choices=[(0, 'not set'), (3, 'viewer'), (2, 'contributor'), (1, 'admin')], default=0, verbose_name='role')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.project')),
            ],
            options={
                'verbose_name': 'request permission project',
                'unique_together': {('email', 'project')},
            },
        ),
    ]
