# Generated by Django 3.2.11 on 2022-04-19 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0037_alter_newsletterlanguage_language"),
        ("common", "0037_auto_20220418_2220"),
    ]

    operations = []
