# Generated by Django 3.2.11 on 2022-02-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0038_auto_20220207_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='RocketAuthorization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.PositiveIntegerField(choices=[(0, 'not set'), (1, 'agent'), (2, 'service manager')], default=0, verbose_name='role')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
        ),
    ]
