# Generated by Django 3.2.11 on 2022-02-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0041_alter_projectauthorization_rocket_authorization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletterlanguage',
            name='language',
            field=models.CharField(choices=[('es', 'Spanish'), ('en-us', 'English'), ('pt-br', 'Portuguese')], default='en-us', max_length=10, verbose_name='language'),
        ),
    ]
