# Generated by Django 3.2.11 on 2022-02-08 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0042_alter_newsletterlanguage_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectauthorization",
            name="rocket_authorization",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.rocketauthorization",
            ),
        ),
    ]
