# Generated by Django 3.2.11 on 2022-03-25 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0036_project_total_contact_count'),
        ('common', '0044_auto_20220303_2024'),
    ]

    operations = [
    ]
