# Generated by Django 3.2.11 on 2022-03-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0045_merge_20220325_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletterlanguage',
            name='language',
            field=models.CharField(choices=[('en-us', 'English'), ('pt-br', 'Portuguese'), ('es', 'Spanish')], default='en-us', max_length=10, verbose_name='language'),
        ),
    ]
