# Generated by Django 3.2.13 on 2022-04-25 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0038_merge_0037_auto_20220324_1811_0037_auto_20220418_2220"),
        ("common", "0045_requestrocketpermission"),
    ]

    operations = []
