# Generated by Django 3.2.11 on 2022-04-29 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0046_merge_20220425_2209'),
        ('common', '0046_merge_20220429_2016'),
    ]

    operations = [
    ]
