# Generated by Django 3.2.13 on 2022-05-02 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0038_merge_20220419_0318'),
        ('common', '0047_merge_20220429_2024'),
    ]

    operations = [
    ]
