# Generated by Django 3.2.12 on 2022-04-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0047_merge_20220413_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingplan',
            name='plan',
            field=models.CharField(choices=[('free', 'free'), ('enterprise', 'enterprise'), ('custom', 'custom')], max_length=10, verbose_name='plan'),
        ),
    ]
