# Generated by Django 3.2.13 on 2022-05-05 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0048_merge_20220502_2037"),
        ("common", "0048_merge_20220505_1235"),
    ]

    operations = []
