# Generated by Django 3.2.13 on 2022-05-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0051_organization_enforce_2fa'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationauthorization',
            name='has_2fa',
            field=models.BooleanField(default=False, verbose_name='2 factor authentication active'),
        ),
    ]
