# Generated by Django 3.2.13 on 2022-05-19 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0050_auto_20220506_1220"),
        ("common", "0051_openedproject"),
    ]

    operations = []
