# Generated by Django 3.2.13 on 2022-06-02 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0051_openedproject'),
        ('common', '0052_organizationauthorization_has_2fa'),
    ]

    operations = [
    ]
