# Generated by Django 3.2.13 on 2022-06-06 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0052_merge_0050_auto_20220506_1220_0051_openedproject"),
        ("common", "0054_alter_organizationauthorization_has_2fa"),
    ]

    operations = []
