# Generated by Django 3.2.13 on 2022-06-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0055_merge_20220606_1437"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationauthorization",
            name="role",
            field=models.PositiveIntegerField(
                choices=[
                    (0, "not set"),
                    (2, "contributor"),
                    (3, "admin"),
                    (1, "viewer"),
                    (4, "financial"),
                    (5, "SUPPORT"),
                ],
                default=0,
                verbose_name="role",
            ),
        ),
        migrations.AlterField(
            model_name="projectauthorization",
            name="role",
            field=models.PositiveIntegerField(
                choices=[
                    (0, "not set"),
                    (1, "viewer"),
                    (2, "contributor"),
                    (3, "moderator"),
                    (4, "support"),
                ],
                default=0,
                verbose_name="role",
            ),
        ),
        migrations.AlterField(
            model_name="requestpermissionorganization",
            name="role",
            field=models.PositiveIntegerField(
                choices=[
                    (0, "not set"),
                    (2, "contributor"),
                    (3, "admin"),
                    (1, "viewer"),
                    (4, "financial"),
                    (5, "SUPPORT"),
                ],
                default=0,
                verbose_name="role",
            ),
        ),
        migrations.AlterField(
            model_name="requestpermissionproject",
            name="role",
            field=models.PositiveIntegerField(
                choices=[
                    (0, "not set"),
                    (1, "viewer"),
                    (2, "contributor"),
                    (3, "moderator"),
                    (4, "support"),
                ],
                default=0,
                verbose_name="role",
            ),
        ),
    ]
