# Generated by Django 3.2.13 on 2022-08-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0059_project_is_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="templateproject",
            name="redirect_url",
            field=models.URLField(null=True),
        ),
    ]
