# Generated by Django 3.2.15 on 2022-09-01 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("common", "0060_templateproject_redirect_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatsAuthorization",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.PositiveIntegerField(
                        choices=[(0, "not set"), (1, "user"), (2, "admin")],
                        default=0,
                        verbose_name="role",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RequestChatsPermission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="email")),
                (
                    "role",
                    models.PositiveIntegerField(
                        choices=[(0, "not set"), (1, "user"), (2, "admin")],
                        default=0,
                        verbose_name="role",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="common.project"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="projectauthorization",
            name="chats_authorization",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.chatsauthorization",
            ),
        ),
    ]
