# Generated by Django 3.2.15 on 2022-10-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0065_project_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingplan",
            name="trial_end_date",
            field=models.DateTimeField(null=True, verbose_name="Trial end date"),
        ),
        migrations.AlterField(
            model_name="billingplan",
            name="plan",
            field=models.CharField(
                choices=[
                    ("free", "free"),
                    ("trial", "trial"),
                    ("basic", "basic"),
                    ("plus", "plus"),
                    ("premium", "premium"),
                    ("enterprise", "enterprise"),
                    ("custom", "custom"),
                ],
                max_length=10,
                verbose_name="plan",
            ),
        ),
    ]
