# Generated by Django 3.2.16 on 2022-12-26 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("common", "0069_recentactivity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recentactivity",
            name="action",
            field=models.CharField(
                choices=[
                    ("CREATE", "Entity Created"),
                    ("UPDATE", "Entity updated"),
                    ("ADD", "Add"),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="recentactivity",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_recent_activity",
                to="common.project",
            ),
        ),
        migrations.AlterField(
            model_name="recentactivity",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_recent_activy",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
