# Generated by Django 3.2.16 on 2022-12-22 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0069_project_template_type'),
        ('common', '0069_recentactivity'),
    ]

    operations = [
    ]
