# Generated by Django 3.2.16 on 2022-12-26 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0070_auto_20221226_1753'),
        ('common', '0070_merge_0069_project_template_type_0069_recentactivity'),
    ]

    operations = [
    ]
