# Generated by Django 3.2.16 on 2023-03-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0072_auto_20230123_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='flow_organization',
            field=models.UUIDField(blank=True, null=True, unique=True, verbose_name='flow identification UUID'),
        ),
    ]
