# Generated by Django 3.2.16 on 2023-02-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0073_alter_recentactivity_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyOrg',
            fields=[
            ],
            options={
                'verbose_name': 'Organization Authorization',
                'verbose_name_plural': 'Organization Authorization',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('common.organization',),
        ),
        migrations.AlterField(
            model_name='project',
            name='flow_organization',
            field=models.UUIDField(blank=True, null=True, unique=True, verbose_name='flow identification UUID'),
        ),
        migrations.AlterField(
            model_name='recentactivity',
            name='action',
            field=models.CharField(choices=[('ADD', 'Add'), ('TRAIN', 'Entity Trained'), ('CREATE', 'Entity Created'), ('INTEGRATE', 'Entity integrated'), ('UPDATE', 'Entity updated')], max_length=15),
        ),
    ]
