# Generated by Django 3.2.18 on 2023-04-06 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0073_auto_20230330_1542'),
        ('common', '0074_auto_20230327_2002'),
    ]

    operations = [
    ]
