# Generated by Django 3.2.16 on 2023-02-24 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0072_auto_20230123_1728'),
        ('common', '0074_auto_20230208_1143'),
    ]

    operations = [
    ]
