# Generated by Django 3.2.18 on 2023-05-08 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0076_auto_20230417_1754'),
        ('common', '0076_auto_20230426_1422'),
    ]

    operations = [
    ]
