# Generated by Django 3.2.18 on 2023-05-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0076_auto_20230417_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentactivity',
            name='action',
            field=models.CharField(choices=[('INTEGRATE', 'Entity integrated'), ('UPDATE', 'Entity updated'), ('ADD', 'Add'), ('CREATE', 'Entity Created'), ('TRAIN', 'Entity Trained')], max_length=15),
        ),
    ]
