# Generated by Django 3.2.18 on 2023-05-11 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0077_alter_recentactivity_action"),
        ("common", "0077_merge_0076_auto_20230417_1754_0076_auto_20230426_1422"),
    ]

    operations = []
