# Generated by Django 3.2.20 on 2023-07-19 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0079_auto_20230523_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentactivity',
            name='action',
            field=models.CharField(choices=[('INTEGRATE', 'Entity integrated'), ('TRAIN', 'Entity Trained'), ('ADD', 'Add'), ('UPDATE', 'Entity updated'), ('CREATE', 'Entity Created')], max_length=15),
        ),
    ]
