# Generated by Django 3.2.18 on 2023-06-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0079_auto_20230523_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentactivity',
            name='action',
            field=models.CharField(choices=[('TRAIN', 'Entity Trained'), ('INTEGRATE', 'Entity integrated'), ('UPDATE', 'Entity updated'), ('ADD', 'Add'), ('CREATE', 'Entity Created')], max_length=15),
        ),
    ]
