# Generated by Django 3.2.20 on 2023-07-26 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('template_projects', '0004_auto_20230726_1828'),
        ('common', '0079_auto_20230523_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_template_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_projects', to='template_projects.templatetype'),
        ),
        migrations.AlterField(
            model_name='recentactivity',
            name='action',
            field=models.CharField(choices=[('INTEGRATE', 'Entity integrated'), ('CREATE', 'Entity Created'), ('UPDATE', 'Entity updated'), ('TRAIN', 'Entity Trained'), ('ADD', 'Add')], max_length=15),
        ),
    ]
