# Generated by Django 3.2.20 on 2023-08-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0080_auto_20230824_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentactivity',
            name='action',
            field=models.CharField(choices=[('UPDATE', 'Entity updated'), ('TRAIN', 'Entity Trained'), ('ADD', 'Add'), ('INTEGRATE', 'Entity integrated'), ('CREATE', 'Entity Created')], max_length=15),
        ),
        migrations.DeleteModel(
            name='RequestChatsPermission',
        ),
    ]
