# Generated by Django 3.2.20 on 2023-09-06 14:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0080_auto_20230824_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentactivity',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Entity Created'), ('UPDATE', 'Entity updated'), ('TRAIN', 'Entity Trained'), ('ADD', 'Add'), ('INTEGRATE', 'Entity integrated')], max_length=15),
        ),
        migrations.AlterField(
            model_name='templateproject',
            name='classifier_uuid',
            field=models.UUIDField(default=uuid.uuid4, null=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='templateproject',
            name='flow_uuid',
            field=models.UUIDField(default=uuid.uuid4, null=True, verbose_name='UUID'),
        ),
    ]
