# Generated by Django 3.2.20 on 2023-09-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0080_auto_20230824_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentactivity',
            name='action',
            field=models.CharField(choices=[('TRAIN', 'Entity Trained'), ('INTEGRATE', 'Entity integrated'), ('ADD', 'Add'), ('CREATE', 'Entity Created'), ('UPDATE', 'Entity updated')], max_length=15),
        ),
    ]
