# Generated by Django 3.2.18 on 2023-06-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0080_alter_recentactivity_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentactivity',
            name='action',
            field=models.CharField(choices=[('UPDATE', 'Entity updated'), ('CREATE', 'Entity Created'), ('TRAIN', 'Entity Trained'), ('INTEGRATE', 'Entity integrated'), ('ADD', 'Add')], max_length=15),
        ),
    ]
