# Generated by Django 3.2.20 on 2023-09-27 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0081_alter_recentactivity_action'),
        ('common', '0081_auto_20230828_1348'),
        ('common', '0081_auto_20230921_1326'),
    ]

    operations = [
    ]
