# Generated by Django 3.2.23 on 2024-07-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0083_auto_20231206_0415"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="require_external_provider_for_access",
            field=models.BooleanField(
                default=False,
                verbose_name="Only users with external provider can access the organization",
            ),
        ),
        migrations.AlterField(
            model_name="recentactivity",
            name="action",
            field=models.CharField(
                choices=[
                    ("UPDATE", "Entity updated"),
                    ("CREATE", "Entity Created"),
                    ("DELETE", "Entity Deleted"),
                    ("ADD", "Add"),
                    ("INTEGRATE", "Entity integrated"),
                    ("TRAIN", "Entity Trained"),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="recentactivity",
            name="entity",
            field=models.CharField(
                choices=[
                    ("USER", "User Entity"),
                    ("FLOW", "Flow Entity"),
                    ("CHANNEL", "Channel Entity"),
                    ("TRIGGER", "Trigger Entity"),
                    ("CAMPAIGN", "Campaign Entity"),
                    ("AI", "Artificial Intelligence Entity"),
                    ("NEXUS", "Artificial Intelligence Entity"),
                ],
                max_length=20,
            ),
        ),
    ]
