# Generated by Django 3.2.23 on 2024-11-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0086_alter_recentactivity_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="type",
            field=models.IntegerField(
                choices=[(1, "general"), (2, "commerce")],
                default=1,
                verbose_name="Project type",
            ),
        ),
    ]
