# Generated by Django 3.2.23 on 2024-11-21 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0087_project_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="type",
            new_name="project_type",
        ),
    ]
