# Generated by Django 3.2 on 2025-08-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0091_project_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingplan",
            name="trial_extension_enabled",
            field=models.BooleanField(default=False, verbose_name="Trial extension enabled"),
        ),
        migrations.AddField(
            model_name="billingplan",
            name="trial_extension_end_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Trial extension end date"),
        ),
    ]


