# Generated by Django 3.2.23 on 2025-09-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0092_billingplan_trial_extension_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingplan',
            name='plan',
            field=models.CharField(choices=[('free', 'free'), ('trial', 'trial'), ('start', 'start'), ('scale', 'scale'), ('advanced', 'advanced'), ('enterprise', 'enterprise'), ('internal_weni', 'internal_weni')], max_length=13, verbose_name='plan'),
        ),
    ]
