# Generated by Django 3.2.23 on 2025-12-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0093_project_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationauthorization',
            name='role',
            field=models.PositiveIntegerField(choices=[(0, 'not set'), (2, 'contributor'), (3, 'admin'), (1, 'viewer'), (4, 'financial'), (5, 'support'), (6, 'marketing')], default=0, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='projectauthorization',
            name='role',
            field=models.PositiveIntegerField(choices=[(0, 'not set'), (1, 'viewer'), (2, 'contributor'), (3, 'moderator'), (4, 'support'), (5, 'Chat user'), (6, 'marketing')], default=0, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='requestpermissionorganization',
            name='role',
            field=models.PositiveIntegerField(choices=[(0, 'not set'), (2, 'contributor'), (3, 'admin'), (1, 'viewer'), (4, 'financial'), (5, 'support'), (6, 'marketing')], default=0, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='requestpermissionproject',
            name='role',
            field=models.PositiveIntegerField(choices=[(0, 'not set'), (1, 'viewer'), (2, 'contributor'), (3, 'moderator'), (4, 'support'), (5, 'Chat user'), (6, 'marketing')], default=0, verbose_name='role'),
        ),
    ]
