# Generated by Django 3.2.23 on 2026-03-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0094_auto_20251203_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='config',
            field=models.JSONField(blank=True, default=dict, verbose_name='Project configuration'),
        ),
    ]
