# Generated by Django 3.2.23 on 2026-05-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0095_project_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletterlanguage',
            name='language',
            field=models.CharField(choices=[('en-us', 'English'), ('pt-br', 'Portuguese'), ('es', 'Spanish'), ('ro', 'Romanian')], default='en-us', max_length=10, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='project',
            name='language',
            field=models.CharField(choices=[('en-us', 'English'), ('pt-br', 'Portuguese'), ('es', 'Spanish'), ('ro', 'Romanian')], default='en-us', max_length=64, null=True, verbose_name='Project Language'),
        ),
    ]
