# Generated by Django 3.2.25 on 2026-09-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0099_project_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationssoconfig',
            name='requires_customer_identity_source',
            field=models.BooleanField(default=False),
        ),
    ]
