# Generated by Django 2.2.19 on 2021-03-31 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="language",
            field=models.CharField(
                choices=[("en-us", "English"), ("pt-br", "Portuguese")],
                default="en-us",
                help_text="The primary language used by this user",
                max_length=64,
                verbose_name="Language",
            ),
        ),
    ]
