# Generated by Django 2.2.19 on 2021-07-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_user_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.IntegerField(
                help_text="Phone number of the user; include area code",
                null=True,
                verbose_name="Telephone Number",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="short_phone_prefix",
            field=models.IntegerField(
                help_text="Phone prefix of the user",
                null=True,
                verbose_name="Phone Prefix Country",
            ),
        ),
    ]
