# Generated by Django 3.2.20 on 2023-10-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_useremailsetup'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_phone_number',
            field=models.BigIntegerField(help_text='company phone number', null=True, verbose_name='company phone number'),
        ),
    ]
