# Generated by Django 3.2.20 on 2023-07-20 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_useremailsetup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useremailsetup',
            old_name='user',
            new_name='user_instance',
        ),
    ]
