# Generated by Django 3.2.23 on 2024-07-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0017_user_company_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="identity_provider",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
