# Generated by Django 3.2.23 on 2024-07-01 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_user_company_phone_number'),
        ('authentication', '0017_user_email_verified'),
    ]

    operations = [
    ]
