# Generated by Django 3.2.23 on 2024-07-01 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_merge_20240701_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_verified',
        ),
    ]
