# Generated by Django 3.2.23 on 2024-08-05 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_auto_20240711_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useridentityprovider',
            name='provider_user_id',
        ),
    ]
