# Generated by Django 3.2.23 on 2026-05-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_remove_useridentityprovider_provider_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en-us', 'English'), ('pt-br', 'Portuguese'), ('es', 'Spanish'), ('ro', 'Romanian')], default='en-us', help_text='The primary language used by this user', max_length=64, verbose_name='Language'),
        ),
    ]
