# Generated by Django 3.2.23 on 2026-06-02 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0096_auto_20260514_1736'),
        ('authentication', '0021_alter_user_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('project_uuid', models.UUIDField()),
                ('project_name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_access', to='common.project')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_access', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
