# Generated by Django 3.2.12 on 2022-04-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncmanagertask',
            name='finished_at',
            field=models.DateTimeField(null=True, verbose_name='finished at'),
        ),
    ]
