# Generated by Django 3.2.13 on 2022-05-13 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="channel",
        ),
        migrations.AddField(
            model_name="contact",
            name="channel_type",
            field=models.CharField(
                default="whatsapp", max_length=150, verbose_name="channel_type"
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="last_seen_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
