# Generated by Django 3.2.13 on 2022-06-08 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_alter_channel_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="syncmanagertask",
            name="fail_message",
            field=models.TextField(null=True),
        ),
    ]
