# Generated by Django 3.2.13 on 2022-06-15 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_syncmanagertask_fail_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='contact name'),
        ),
    ]
