# Generated by Django 3.2.20 on 2023-08-30 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0009_contactcount_day"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="channel",
        ),
        migrations.RemoveField(
            model_name="contactcount",
            name="channel",
        ),
        migrations.DeleteModel(
            name="Channel",
        ),
    ]
